import type { PricingPlan } from './types'

export const plans: PricingPlan[] = [
  {
    id: 'starter',
    label: 'Başlangıç',
    monthlyPrice: '₺0',
    yearlyPrice: '₺0',
    monthlyPeriod: '14 gün',
    yearlyPeriod: '14 gün',
    monthlyDescription: 'Sistemi denemek için ücretsiz başlangıç.',
    yearlyDescription: 'Sistemi denemek için ücretsiz başlangıç.',
    features: [
      { text: '14 gün ücretsiz deneme', included: true },
      { text: '10 randevu hakkı', included: true },
      { text: 'Temel takvim & profil', included: true },
      { text: 'WhatsApp hatırlatma', included: false },
      { text: 'Tema özelleştirme', included: false },
    ],
    ctaText: 'Ücretsiz başla',
    ctaHref: '/kayit',
    featured: false,
  },
  {
    id: 'pro',
    label: 'Profesyonel',
    monthlyPrice: '₺699',
    yearlyPrice: '₺6.990',
    monthlyPeriod: '/ay',
    yearlyPeriod: '/yıl',
    monthlyDescription: 'Aktif kullanan bireysel uzmanlar için.',
    yearlyDescription: '2 ay bedava · aylık ₺582,5\'e denk gelir',
    features: [
      { text: 'Sınırsız randevu', included: true },
      { text: 'WhatsApp hatırlatma (500/ay)', included: true },
      { text: 'Raporlama paneli', included: true },
      { text: 'Özel slug link', included: true },
      { text: 'Tema & renk özelleştirme', included: true },
    ],
    ctaText: 'Satın Al',
    ctaHref: '/kayit',
    featured: true,
  },
  {
    id: 'corporate',
    label: 'Kurumsal',
    monthlyPrice: '₺1.299',
    yearlyPrice: '₺12.990',
    monthlyPeriod: '/ay',
    yearlyPeriod: '/yıl',
    monthlyDescription: 'Çoklu uzmanlı yapılar için tek panel.',
    yearlyDescription: '2 ay bedava · aylık ₺1.082,5\'e denk gelir',
    features: [
      { text: '10 uzman koltuğu', included: true },
      { text: 'Merkezi yönetim paneli', included: true },
      { text: 'WhatsApp hatırlatma (sınırsız)', included: true },
      { text: 'Tema & renk özelleştirme', included: true },
      { text: 'Öncelikli destek', included: true },
    ],
    ctaText: 'Satın Al',
    ctaHref: '/kayit',
    featured: false,
  },
]