import type { Profession } from './types'

export const professions: Profession[] = [
  {
    title: 'Psikolog & Terapist',
    description: '50dk seans, online/yüz yüze randevu, KVKK uyumlu notlar.',
    emoji: '🧠',
    iconBg: 'bg-rose-50',
    href: '/profil',
    statLabel: 'uzman',
    statCount: '3.412',
    rating: '4.9',
  },
  {
    title: 'Diyetisyen',
    description: 'Beden ölçümleri, takip seansları, beslenme planı paylaşımı.',
    emoji: '🥗',
    iconBg: 'bg-emerald-50',
    href: '/profil',
    statLabel: 'uzman',
    statCount: '1.847',
    rating: '4.8',
  },
  {
    title: 'Avukat',
    description: 'Danışmanlık görüşmesi, dosya kategorileri, çoklu konuk desteği.',
    emoji: '⚖️',
    iconBg: 'bg-slate-100',
    href: '/profil',
    statLabel: 'uzman',
    statCount: '2.103',
    rating: '4.9',
  },
  {
    title: 'Veteriner Klinikleri',
    description: 'Çoklu veteriner, hayvan profili, acil randevu önceliği.',
    emoji: '🐾',
    iconBg: 'bg-amber-50',
    href: '/kurumsal',
    statLabel: 'klinik',
    statCount: '926',
    rating: '4.8',
  },
  {
    title: 'Diş Klinikleri',
    description: 'Birden çok hekim, tedavi tipine göre süre, koltuk yönetimi.',
    emoji: '🦷',
    iconBg: 'bg-sky-50',
    href: '/kurumsal',
    statLabel: 'klinik',
    statCount: '1.512',
    rating: '4.9',
  },
  {
    title: 'Güzellik Salonu',
    description: 'Cilt bakımı, makyaj, manikür/pedikür — tüm hizmetler tek panelde.',
    emoji: '💄',
    iconBg: 'bg-pink-50',
    href: '/profil',
    statLabel: 'salon',
    statCount: '2.450',
    rating: '4.8',
  },
  {
    title: 'Kuaför',
    description: 'Saç kesimi, boyama, bakım — birden çok personel ve hizmet türü.',
    emoji: '💇',
    iconBg: 'bg-indigo-50',
    href: '/profil',
    statLabel: 'kuaför',
    statCount: '3.180',
    rating: '4.7',
  },
]